---
abstract: 'simple DAV server for Plack'
author:
  - 'Nobuo Danjou <nobuo.danjou@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-DAV
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filesys::Virtual::Plain: 0
  HTTP::Request: 0
  Net::DAV::Server: 0
  Plack: 0.9021
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lopnor/Plack-App-DAV.git
version: 0.02
